package ExerCh4

public enum class Christmas12Days(val item: String){
    PARTRIDGE("PARTRIDGE"), TURTLEDOVES("TURTLE DOVES"), FRENCHHENS("FRENCH HENS"), CALLINGBIRDS("CALLING BIRDS"), GOLDRINGS("GOLD RINGS"), GEESE("GEESE"),
    SWANS("SWANS"), MAIDS("MAIDS"), LADIES("LADIES"), LORDS("LORDS"), PIPERS("PIPERS"), DRUMMERS("DRUMMERS")
}